export default [
  {
    "_id": "Q101",
    "title": "Q1 - HTML",
    "course": "RS101",
    "description": "Basic HTML knowledge",
    "quizType": "Graded Quiz",
    "assignmentGroup": "Quizzes",
    "shuffleAnswers": true,
    "timeLimit": 20, // minutes
    "multipleAttempts": false,
    "showCorrectAnswers": true,
    "oneQuestionAtATime": true,
    "webcamRequired": false,
    "lockQuestionsAfterAnswering": false,
    "points": 29,
    "due": "2024-05-21",
    "availableDate": "2024-05-15",
    "untilDate": "2024-05-22",
    "published": false,
    "questionsCount": 11
  },
  {
    "_id": "Q102",
    "title": "Q2 - CSS",
    "course": "RS101",
    "description": "CSS Selectors and Box Model",
    "quizType": "Graded Quiz",
    "assignmentGroup": "Quizzes",
    "shuffleAnswers": true,
    "timeLimit": 20,
    "multipleAttempts": true,
    "howManyAttempts": 3,
    "showCorrectAnswers": false,
    "oneQuestionAtATime": false,
    "webcamRequired": false,
    "lockQuestionsAfterAnswering": false,
    "points": 32,
    "due": "2024-05-28",
    "availableDate": "2024-05-20",
    "untilDate": "2024-05-29",
    "published": true,
    "questionsCount": 7
  },
  {
    "_id": "Q103",
    "title": "EXAM 1 - React",
    "course": "RS101",
    "description": "Midterm Exam",
    "quizType": "Exam",
    "assignmentGroup": "Exams",
    "shuffleAnswers": false,
    "timeLimit": 90,
    "multipleAttempts": false,
    "showCorrectAnswers": false,
    "oneQuestionAtATime": true,
    "webcamRequired": true,
    "lockQuestionsAfterAnswering": true,
    "points": 100,
    "due": "2024-06-10",
    "availableDate": "2024-06-01",
    "untilDate": "2024-06-10",
    "published": true,
    "questionsCount": 25
  }
];